CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXPL_WORK_ORDER_TRANS_HDR_ID_V" ("WO_SCH_MAIN_HDR_ID", "INTERFACE_STATUS", "RESOURCETABLEID", "WOOPERATIONID", "WORKORDERID", "BASISTYPE", "RESOURCECODE", "REQUIREDUSAGE", "RESOURCESEQUENCENUMBER", "USAGERATE", "PLANNEDSTARTDATE", "PLANNEDCOMPLETIONDATE", "WOOPERATIONRESOURCEID", "PAYLOAD_TYPE") 
AS 
select 
WOH.WO_SCH_MAIN_HDR_ID as WO_SCH_MAIN_HDR_ID,
WOH.INTERFACE_STATUS as INTERFACE_STATUS,
WOS.SC_TNX_RESOURCE_ID as resourcetableId,
WOS.WO_OP_ID as WoOperationId, 
WOS.WO_ID as WorkOrderId,
1 as BasisType,
WOS.RESOURCES as ResourceCode,
1 as RequiredUsage,
WOS.RESOURCE_SEQUENCE_NUMBER as ResourceSequenceNumber,
1 as UsageRate,
TO_CHAR((WOS.START_DATE), 'yyyy-MM-dd"T"HH24:MI:SS')||'+00:00' as PlannedStartDate,
TO_CHAR((WOS.COMPLETE_DATE  + 1/24), 'yyyy-MM-dd"T"HH24:MI:SS')||'+00:00' as PlannedCompletionDate,
WOOPERATIONRESOURCEID,
CASE
when WOOPERATIONRESOURCEID is NULL THEN 'NEW'
when WOOPERATIONRESOURCEID is NOT NULL THEN 'UPDATE'
ELSE 'ERROR'
END AS PAYLOAD_TYPE

from 
XXPM_WO_SCHEDULING_MAIN_HDR WOH,
XXPM_SCHEDULER_TNX WOP, 
XXPM_SCHEDULER_RESOURCE WOS 
WHERE 
WOH.WO_SCH_MAIN_HDR_ID=WOP.WO_SCH_MAIN_HDR_ID
AND WOP.SC_WO_TNX_ID=WOS.SC_WO_TNX_ID
and WOH.WO_SCH_MAIN_HDR_ID=WOP.WO_SCH_MAIN_HDR_ID
and NVL(WOP.STATUS, 'XXX') NOT IN ('Rework')
--AND INTERFACE_STATUS IN ('TRANSFER_WORK_ORDER')
--and WOS.ATTRIBUTE1 is null
--and WOH.WO_SCH_MAIN_HDR_ID=01
;
